-- MySQL Script generated by MySQL Workbench
-- Sun Jan 17 09:31:46 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jeththu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jeththu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jeththu` DEFAULT CHARACTER SET utf8 ;
USE `jeththu` ;

-- -----------------------------------------------------
-- Table `jeththu`.`cutomer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jeththu`.`cutomer` (
  `customer_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `gender` VARCHAR(10) NULL,
  `address` VARCHAR(250) NULL,
  `contact_number` VARCHAR(15) NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jeththu`.`order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jeththu`.`order_status` (
  `id` INT NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `description` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `status_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jeththu`.`payment_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jeththu`.`payment_status` (
  `id` INT NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jeththu`.`jet_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jeththu`.`jet_order` (
  `jet_order_id` INT NOT NULL,
  `order_date` DATETIME NULL,
  `due_date` DATETIME NULL,
  `Description` VARCHAR(200) NULL,
  `customer_id` INT NOT NULL,
  `order_status_id` INT NOT NULL,
  `gross_total` DECIMAL(9,2) NULL,
  `paid_amount` DECIMAL(9,2) NULL,
  `payment_status_id` INT NOT NULL,
  PRIMARY KEY (`jet_order_id`),
  INDEX `fk_jet_order_cutomer1_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_jet_order_order_status1_idx` (`order_status_id` ASC) VISIBLE,
  INDEX `fk_jet_order_payment_status1_idx` (`payment_status_id` ASC) VISIBLE,
  CONSTRAINT `fk_jet_order_cutomer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `jeththu`.`cutomer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jet_order_order_status1`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `jeththu`.`order_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jet_order_payment_status1`
    FOREIGN KEY (`payment_status_id`)
    REFERENCES `jeththu`.`payment_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jeththu`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jeththu`.`item` (
  `intem_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `details` VARCHAR(200) NULL,
  PRIMARY KEY (`intem_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jeththu`.`Payment_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jeththu`.`Payment_history` (
  `payment_id` INT NOT NULL,
  `amount` DECIMAL(9,2) NOT NULL,
  `paid_date` DATETIME NULL,
  `jet_order_id` INT NOT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `fk_Payment_history_jet_order1_idx` (`jet_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_Payment_history_jet_order1`
    FOREIGN KEY (`jet_order_id`)
    REFERENCES `jeththu`.`jet_order` (`jet_order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jeththu`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jeththu`.`order_item` (
  `jet_order_jet_order_id` INT NOT NULL,
  `item_intem_id` INT NOT NULL,
  `quntity` DECIMAL(3,0) NULL,
  `sub_total` DECIMAL(8,2) NULL,
  INDEX `fk_order_item_jet_order1_idx` (`jet_order_jet_order_id` ASC) VISIBLE,
  INDEX `fk_order_item_item1_idx` (`item_intem_id` ASC) VISIBLE,
  PRIMARY KEY (`jet_order_jet_order_id`, `item_intem_id`),
  CONSTRAINT `fk_order_item_jet_order1`
    FOREIGN KEY (`jet_order_jet_order_id`)
    REFERENCES `jeththu`.`jet_order` (`jet_order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_item_item1`
    FOREIGN KEY (`item_intem_id`)
    REFERENCES `jeththu`.`item` (`intem_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
